[versions]
apollo = "4.2.0"
junit = "5.12.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
spring-boot = { id = "org.springframework.boot", version = "3.4.5" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.3.1" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version = "2.1.20" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.1.20" }

[libraries]
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
