[versions]
apollo = "4.3.3"
junit = "6.0.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
spring-boot = { id = "org.springframework.boot", version = "4.0.0" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.4.5" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version = "2.2.21" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.2.21" }

[libraries]
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
