[versions]
apollo = "4.1.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }

[libraries]
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo"}
